/* ------------------------------------------------------------------ */
/*  CapStoned — Mock data (Career OS foundation)                        */
/*                                                                      */
/*  Realistic inline sample data to make dashboards look alive:         */
/*  10 tracks across varied orgs/domains, 16 candidate profiles across  */
/*  varied animals/skills, and 2 university cohorts with engagement     */
/*  rows, a populated interest heatmap, and a mismatch-averted figure.  */
/*                                                                      */
/*  Deterministic and side-effect free.                                 */
/* ------------------------------------------------------------------ */

import {
  DEFAULT_FACTOR_WEIGHTS,
  type CandidateProfile,
  type Cohort,
  type InterestHeatmap,
  type MismatchAverted,
  type StudentEngagement,
  type Track,
} from './domain'

/* ================================================================== */
/*  Tracks                                                             */
/* ================================================================== */

export const TRACKS: Track[] = [
  {
    id: 'trk-fe-arch',
    title: 'Frontend Architecture Mentorship',
    org: 'Talentbank',
    department: 'Web Platform',
    summary:
      'Ship real UI on the partner dashboard while learning component architecture, testing, and design-system discipline.',
    objectives: [
      'Own a user-facing feature end to end',
      'Reach production-grade test coverage on your modules',
      'Adopt the squad’s written-first async workflow',
    ],
    deliverables: [
      'A merged feature behind a feature flag',
      'A component with 80%+ test coverage',
      'An onboarding runbook for the next mentee',
    ],
    milestones: [
      { id: 'm1', week: 2, title: 'First reviewed PR to staging', detail: 'Small, scoped, merged with review.' },
      { id: 'm2', week: 6, title: 'Own a feature end-to-end', detail: 'From spec to shipped behind a flag.' },
      { id: 'm3', week: 8, title: 'Lead a squad demo', detail: 'Present your work at sprint review.' },
      { id: 'm4', week: 12, title: 'Hit coverage + runbook', detail: 'Close out quality and documentation.' },
    ],
    durationWeeks: 12,
    intensity: 'moderate',
    weeklyHours: 10,
    cap: 4,
    applicants: 37,
    requiredSkills: [
      { name: 'React', weight: 0.35, targetLevel: 70 },
      { name: 'TypeScript', weight: 0.3, targetLevel: 70 },
      { name: 'CSS', weight: 0.2, targetLevel: 60 },
      { name: 'Testing', weight: 0.15, targetLevel: 55 },
    ],
    domainTags: ['frontend', 'web', 'design-systems'],
    interestTags: ['frontend', 'ui-engineering', 'design-systems'],
    aspirationTags: ['software-engineer', 'frontend-specialist'],
    cultureAnimalAffinity: { beaver: 90, octopus: 70, peacock: 55 },
    factorWeights: { ...DEFAULT_FACTOR_WEIGHTS },
  },
  {
    id: 'trk-data-sci',
    title: 'Applied Data Science Track',
    org: 'Gamuda',
    department: 'Analytics & AI',
    summary:
      'Turn messy construction telemetry into models that inform real decisions on active sites.',
    objectives: [
      'Frame a business question as a modelling problem',
      'Ship a validated predictive model',
      'Communicate findings to non-technical stakeholders',
    ],
    deliverables: [
      'A cleaned, documented dataset',
      'A model with an honest evaluation writeup',
      'A stakeholder-ready findings deck',
    ],
    milestones: [
      { id: 'm1', week: 3, title: 'Data audit complete', detail: 'Quality report on the raw telemetry.' },
      { id: 'm2', week: 7, title: 'Baseline model', detail: 'First model beating the naive baseline.' },
      { id: 'm3', week: 12, title: 'Findings presentation', detail: 'Present to the site operations team.' },
    ],
    durationWeeks: 12,
    intensity: 'intense',
    weeklyHours: 14,
    cap: 3,
    applicants: 24,
    requiredSkills: [
      { name: 'Python', weight: 0.35, targetLevel: 75 },
      { name: 'Statistics', weight: 0.3, targetLevel: 70 },
      { name: 'SQL', weight: 0.2, targetLevel: 60 },
      { name: 'Machine Learning', weight: 0.15, targetLevel: 55 },
    ],
    domainTags: ['data', 'analytics', 'machine-learning'],
    interestTags: ['data', 'analytics', 'machine-learning'],
    aspirationTags: ['data-scientist', 'ml-engineer'],
    cultureAnimalAffinity: { owl: 92, tortoise: 78, beaver: 55 },
    factorWeights: { technicalSkills: 0.4, interests: 0.15, aspirations: 0.15, workingStyle: 0.2, commitment: 0.1 },
  },
  {
    id: 'trk-product-strategy',
    title: 'Product Strategy Fellowship',
    org: 'Grab',
    department: 'Product',
    summary:
      'Sit inside a product pod and learn how bets are framed, prioritised, and killed.',
    objectives: [
      'Write a crisp product brief',
      'Run a prioritisation exercise with real trade-offs',
      'Pitch a bet to the pod lead',
    ],
    deliverables: [
      'A one-page product brief',
      'A prioritised opportunity backlog',
      'A recorded pitch with a decision log',
    ],
    milestones: [
      { id: 'm1', week: 2, title: 'Problem framing', detail: 'Define the opportunity space.' },
      { id: 'm2', week: 6, title: 'Prioritisation', detail: 'Rank opportunities with a scoring model.' },
      { id: 'm3', week: 10, title: 'Bet pitch', detail: 'Pitch and capture the decision.' },
    ],
    durationWeeks: 10,
    intensity: 'moderate',
    weeklyHours: 8,
    cap: 5,
    applicants: 41,
    requiredSkills: [
      { name: 'Product Sense', weight: 0.35, targetLevel: 65 },
      { name: 'Analytics', weight: 0.25, targetLevel: 60 },
      { name: 'Communication', weight: 0.25, targetLevel: 70 },
      { name: 'User Research', weight: 0.15, targetLevel: 55 },
    ],
    domainTags: ['product', 'strategy', 'business'],
    interestTags: ['product', 'strategy', 'business'],
    aspirationTags: ['product-manager', 'strategist'],
    cultureAnimalAffinity: { eagle: 90, lion: 68, fox: 60 },
    factorWeights: { technicalSkills: 0.2, interests: 0.25, aspirations: 0.2, workingStyle: 0.25, commitment: 0.1 },
  },
  {
    id: 'trk-brand-design',
    title: 'Brand & Content Design Studio',
    org: 'AirAsia',
    department: 'Brand Studio',
    summary:
      'Craft campaign-ready brand and content work under the eye of a senior creative director.',
    objectives: [
      'Develop a distinctive visual concept',
      'Produce a multi-format content set',
      'Defend your creative choices in a crit',
    ],
    deliverables: [
      'A mood board and concept rationale',
      'A three-format campaign set',
      'A presented final crit',
    ],
    milestones: [
      { id: 'm1', week: 2, title: 'Concept locked', detail: 'Direction approved by the CD.' },
      { id: 'm2', week: 5, title: 'First formats', detail: 'Initial executions in review.' },
      { id: 'm3', week: 8, title: 'Final crit', detail: 'Present the campaign set.' },
    ],
    durationWeeks: 8,
    intensity: 'moderate',
    weeklyHours: 9,
    cap: 4,
    applicants: 29,
    requiredSkills: [
      { name: 'Visual Design', weight: 0.4, targetLevel: 70 },
      { name: 'Figma', weight: 0.25, targetLevel: 65 },
      { name: 'Copywriting', weight: 0.2, targetLevel: 55 },
      { name: 'Brand Strategy', weight: 0.15, targetLevel: 50 },
    ],
    domainTags: ['design', 'brand', 'content'],
    interestTags: ['design', 'brand', 'creative'],
    aspirationTags: ['designer', 'creative-director'],
    cultureAnimalAffinity: { peacock: 94, eagle: 55, octopus: 50 },
    factorWeights: { technicalSkills: 0.3, interests: 0.25, aspirations: 0.15, workingStyle: 0.25, commitment: 0.05 },
  },
  {
    id: 'trk-backend-plat',
    title: 'Backend Platform Engineering',
    org: 'Setel',
    department: 'Core Platform',
    summary:
      'Work on the services that keep payments flowing — reliability, observability, and clean APIs.',
    objectives: [
      'Add an endpoint with full test coverage',
      'Improve one service’s observability',
      'Participate in an on-call shadow',
    ],
    deliverables: [
      'A shipped, tested API endpoint',
      'A dashboard for a key service metric',
      'An on-call shadow writeup',
    ],
    milestones: [
      { id: 'm1', week: 3, title: 'First endpoint', detail: 'Merged with tests and docs.' },
      { id: 'm2', week: 8, title: 'Observability win', detail: 'A metric dashboard others use.' },
      { id: 'm3', week: 12, title: 'On-call shadow', detail: 'Shadow a full rotation.' },
    ],
    durationWeeks: 12,
    intensity: 'intense',
    weeklyHours: 12,
    cap: 3,
    applicants: 18,
    requiredSkills: [
      { name: 'Go', weight: 0.3, targetLevel: 65 },
      { name: 'SQL', weight: 0.25, targetLevel: 70 },
      { name: 'System Design', weight: 0.25, targetLevel: 60 },
      { name: 'Testing', weight: 0.2, targetLevel: 65 },
    ],
    domainTags: ['backend', 'platform', 'infrastructure'],
    interestTags: ['backend', 'infrastructure', 'distributed-systems'],
    aspirationTags: ['software-engineer', 'platform-engineer'],
    cultureAnimalAffinity: { beaver: 88, tortoise: 72, owl: 60 },
    factorWeights: { technicalSkills: 0.4, interests: 0.15, aspirations: 0.15, workingStyle: 0.2, commitment: 0.1 },
  },
  {
    id: 'trk-growth-mktg',
    title: 'Growth Marketing Sprint',
    org: 'Carsome',
    department: 'Growth',
    summary:
      'Run real experiments on a live funnel and learn how growth teams reason about evidence.',
    objectives: [
      'Design and ship an A/B experiment',
      'Read results honestly',
      'Recommend a scale-or-kill decision',
    ],
    deliverables: [
      'An experiment brief with a hypothesis',
      'A results readout',
      'A scale-or-kill recommendation',
    ],
    milestones: [
      { id: 'm1', week: 2, title: 'Experiment live', detail: 'First test running on the funnel.' },
      { id: 'm2', week: 5, title: 'Readout', detail: 'Honest results with confidence.' },
      { id: 'm3', week: 8, title: 'Recommendation', detail: 'Present scale-or-kill.' },
    ],
    durationWeeks: 8,
    intensity: 'moderate',
    weeklyHours: 8,
    cap: 5,
    applicants: 33,
    requiredSkills: [
      { name: 'Marketing', weight: 0.3, targetLevel: 60 },
      { name: 'Analytics', weight: 0.3, targetLevel: 65 },
      { name: 'Communication', weight: 0.25, targetLevel: 65 },
      { name: 'Copywriting', weight: 0.15, targetLevel: 50 },
    ],
    domainTags: ['marketing', 'growth', 'experimentation'],
    interestTags: ['marketing', 'growth', 'business'],
    aspirationTags: ['growth-marketer', 'marketer'],
    cultureAnimalAffinity: { dolphin: 88, fox: 72, eagle: 55 },
    factorWeights: { technicalSkills: 0.2, interests: 0.3, aspirations: 0.15, workingStyle: 0.25, commitment: 0.1 },
  },
  {
    id: 'trk-ops-delivery',
    title: 'Operations & Delivery Track',
    org: 'Ninja Van',
    department: 'Operations',
    summary:
      'Own a slice of the delivery operation and learn to make decisive calls under real constraints.',
    objectives: [
      'Map and improve one operational process',
      'Run a daily stand-up',
      'Hit a delivery KPI',
    ],
    deliverables: [
      'A process map with a proposed fix',
      'A week of run stand-ups',
      'A KPI movement writeup',
    ],
    milestones: [
      { id: 'm1', week: 2, title: 'Process mapped', detail: 'Current-state map complete.' },
      { id: 'm2', week: 6, title: 'Fix shipped', detail: 'Improvement live in ops.' },
      { id: 'm3', week: 10, title: 'KPI review', detail: 'Show the movement.' },
    ],
    durationWeeks: 10,
    intensity: 'intense',
    weeklyHours: 12,
    cap: 4,
    applicants: 21,
    requiredSkills: [
      { name: 'Operations', weight: 0.35, targetLevel: 60 },
      { name: 'Analytics', weight: 0.25, targetLevel: 55 },
      { name: 'Communication', weight: 0.25, targetLevel: 65 },
      { name: 'Project Management', weight: 0.15, targetLevel: 55 },
    ],
    domainTags: ['operations', 'logistics', 'delivery'],
    interestTags: ['operations', 'logistics', 'business'],
    aspirationTags: ['operations-manager', 'program-manager'],
    cultureAnimalAffinity: { wolf: 90, ant: 74, bee: 66 },
    factorWeights: { technicalSkills: 0.2, interests: 0.2, aspirations: 0.2, workingStyle: 0.3, commitment: 0.1 },
  },
  {
    id: 'trk-qa-quality',
    title: 'Quality Engineering Apprenticeship',
    org: 'MoneyLion',
    department: 'Quality',
    summary:
      'Build the test infrastructure that lets a fintech ship fast without breaking trust.',
    objectives: [
      'Write an automated test suite for a flow',
      'Find and file real defects',
      'Improve one CI signal',
    ],
    deliverables: [
      'An automated end-to-end suite',
      'A triaged defect log',
      'A faster or clearer CI check',
    ],
    milestones: [
      { id: 'm1', week: 3, title: 'First suite', detail: 'Covering a critical flow.' },
      { id: 'm2', week: 7, title: 'Defect hunt', detail: 'Real bugs, well documented.' },
      { id: 'm3', week: 12, title: 'CI improvement', detail: 'A signal the team trusts.' },
    ],
    durationWeeks: 12,
    intensity: 'moderate',
    weeklyHours: 10,
    cap: 4,
    applicants: 15,
    requiredSkills: [
      { name: 'Testing', weight: 0.4, targetLevel: 65 },
      { name: 'JavaScript', weight: 0.25, targetLevel: 60 },
      { name: 'Attention to Detail', weight: 0.2, targetLevel: 70 },
      { name: 'CI/CD', weight: 0.15, targetLevel: 50 },
    ],
    domainTags: ['qa', 'testing', 'quality'],
    interestTags: ['qa', 'testing', 'quality'],
    aspirationTags: ['qa-engineer', 'software-engineer'],
    cultureAnimalAffinity: { owl: 86, tortoise: 74, ant: 62 },
    factorWeights: { technicalSkills: 0.35, interests: 0.2, aspirations: 0.15, workingStyle: 0.2, commitment: 0.1 },
  },
  {
    id: 'trk-startup-generalist',
    title: 'Startup Generalist Residency',
    org: 'Kapital DX',
    department: 'Founders Office',
    summary:
      'Sit next to the founders and do whatever moves the needle — the ultimate ambiguity trial.',
    objectives: [
      'Take a fuzzy problem to a shipped outcome',
      'Wear at least three different hats',
      'Report directly to a founder',
    ],
    deliverables: [
      'A shipped outcome from a vague brief',
      'A log of the hats you wore',
      'A founder-facing retro',
    ],
    milestones: [
      { id: 'm1', week: 2, title: 'First win', detail: 'Something shipped, however small.' },
      { id: 'm2', week: 6, title: 'Multi-hat proof', detail: 'Three domains touched.' },
      { id: 'm3', week: 10, title: 'Founder retro', detail: 'Reflect with the founder.' },
    ],
    durationWeeks: 10,
    intensity: 'intense',
    weeklyHours: 13,
    cap: 2,
    applicants: 47,
    requiredSkills: [
      { name: 'Adaptability', weight: 0.3, targetLevel: 70 },
      { name: 'Communication', weight: 0.25, targetLevel: 65 },
      { name: 'Product Sense', weight: 0.25, targetLevel: 55 },
      { name: 'JavaScript', weight: 0.2, targetLevel: 50 },
    ],
    domainTags: ['startup', 'generalist', 'product'],
    interestTags: ['startup', 'product', 'business'],
    aspirationTags: ['founder', 'product-manager', 'generalist'],
    cultureAnimalAffinity: { fox: 92, octopus: 80, eagle: 58 },
    factorWeights: { technicalSkills: 0.15, interests: 0.25, aspirations: 0.2, workingStyle: 0.3, commitment: 0.1 },
  },
  {
    id: 'trk-people-ops',
    title: 'People & Talent Operations Track',
    org: 'Talentbank',
    department: 'People Team',
    summary:
      'Learn how great talent teams run — hiring signals, onboarding, and the human side of scaling.',
    objectives: [
      'Improve one step of the hiring funnel',
      'Run a structured interview',
      'Ship an onboarding improvement',
    ],
    deliverables: [
      'A funnel improvement proposal',
      'A structured interview scorecard',
      'An onboarding change, shipped',
    ],
    milestones: [
      { id: 'm1', week: 3, title: 'Funnel audit', detail: 'Find the leaky step.' },
      { id: 'm2', week: 6, title: 'Structured interview', detail: 'Run one with a scorecard.' },
      { id: 'm3', week: 9, title: 'Onboarding ship', detail: 'A real improvement live.' },
    ],
    durationWeeks: 9,
    intensity: 'light',
    weeklyHours: 6,
    cap: 4,
    applicants: 26,
    requiredSkills: [
      { name: 'Communication', weight: 0.35, targetLevel: 70 },
      { name: 'People Skills', weight: 0.3, targetLevel: 65 },
      { name: 'Organisation', weight: 0.2, targetLevel: 60 },
      { name: 'Analytics', weight: 0.15, targetLevel: 45 },
    ],
    domainTags: ['people', 'talent', 'operations'],
    interestTags: ['people', 'talent', 'business'],
    aspirationTags: ['people-ops', 'operations-manager'],
    cultureAnimalAffinity: { dolphin: 84, lion: 66, bee: 62 },
    factorWeights: { technicalSkills: 0.15, interests: 0.25, aspirations: 0.2, workingStyle: 0.3, commitment: 0.1 },
  },
]

/* ================================================================== */
/*  Candidate profiles                                                */
/* ================================================================== */

export const CANDIDATES: CandidateProfile[] = [
  {
    id: 'cand-john-doe',
    name: 'John Doe',
    headline: 'Penultimate-year Software Engineering student',
    university: 'Sunway University',
    program: 'BSc Software Engineering',
    skills: [
      { name: 'React', level: 82 },
      { name: 'TypeScript', level: 78 },
      { name: 'CSS', level: 70 },
      { name: 'Testing', level: 58 },
    ],
    interests: ['frontend', 'ui-engineering', 'design-systems'],
    aspirations: ['software-engineer', 'frontend-specialist'],
    availabilityHoursPerWeek: 12,
    animalKey: 'beaver',
    reliabilityScore: 96,
  },
  {
    id: 'cand-aisha-rahman',
    name: 'Aisha Rahman',
    headline: 'Data-curious statistics major',
    university: 'University of Malaya',
    program: 'BSc Statistics',
    skills: [
      { name: 'Python', level: 84 },
      { name: 'Statistics', level: 80 },
      { name: 'SQL', level: 66 },
      { name: 'Machine Learning', level: 58 },
    ],
    interests: ['data', 'analytics', 'machine-learning'],
    aspirations: ['data-scientist', 'ml-engineer'],
    availabilityHoursPerWeek: 15,
    animalKey: 'owl',
    reliabilityScore: 92,
  },
  {
    id: 'cand-marcus-tan',
    name: 'Marcus Tan',
    headline: 'Product-minded business undergrad',
    university: 'Monash University Malaysia',
    program: 'BBus Management',
    skills: [
      { name: 'Product Sense', level: 68 },
      { name: 'Analytics', level: 62 },
      { name: 'Communication', level: 80 },
      { name: 'User Research', level: 55 },
    ],
    interests: ['product', 'strategy', 'business'],
    aspirations: ['product-manager', 'strategist'],
    availabilityHoursPerWeek: 9,
    animalKey: 'eagle',
    reliabilityScore: 88,
  },
  {
    id: 'cand-priya-nair',
    name: 'Priya Nair',
    headline: 'Visual designer with a systems streak',
    university: 'The One Academy',
    program: 'Dip Digital Design',
    skills: [
      { name: 'Visual Design', level: 86 },
      { name: 'Figma', level: 82 },
      { name: 'Copywriting', level: 58 },
      { name: 'Brand Strategy', level: 52 },
    ],
    interests: ['design', 'brand', 'creative'],
    aspirations: ['designer', 'creative-director'],
    availabilityHoursPerWeek: 10,
    animalKey: 'peacock',
    reliabilityScore: 90,
  },
  {
    id: 'cand-wei-lim',
    name: 'Wei Lim',
    headline: 'Backend-leaning CS student',
    university: 'Universiti Sains Malaysia',
    program: 'BCS Computer Science',
    skills: [
      { name: 'Go', level: 62 },
      { name: 'SQL', level: 74 },
      { name: 'System Design', level: 58 },
      { name: 'Testing', level: 66 },
    ],
    interests: ['backend', 'infrastructure', 'distributed-systems'],
    aspirations: ['software-engineer', 'platform-engineer'],
    availabilityHoursPerWeek: 11,
    animalKey: 'tortoise',
    reliabilityScore: 94,
  },
  {
    id: 'cand-hana-yusof',
    name: 'Hana Yusof',
    headline: 'Growth and storytelling enthusiast',
    university: 'Taylor’s University',
    program: 'BA Marketing',
    skills: [
      { name: 'Marketing', level: 72 },
      { name: 'Analytics', level: 64 },
      { name: 'Communication', level: 82 },
      { name: 'Copywriting', level: 70 },
    ],
    interests: ['marketing', 'growth', 'business'],
    aspirations: ['growth-marketer', 'marketer'],
    availabilityHoursPerWeek: 8,
    animalKey: 'dolphin',
    reliabilityScore: 87,
  },
  {
    id: 'cand-daniel-ong',
    name: 'Daniel Ong',
    headline: 'Ops-minded industrial engineering student',
    university: 'Universiti Teknologi Malaysia',
    program: 'BEng Industrial',
    skills: [
      { name: 'Operations', level: 66 },
      { name: 'Analytics', level: 60 },
      { name: 'Communication', level: 68 },
      { name: 'Project Management', level: 58 },
    ],
    interests: ['operations', 'logistics', 'business'],
    aspirations: ['operations-manager', 'program-manager'],
    availabilityHoursPerWeek: 13,
    animalKey: 'wolf',
    reliabilityScore: 91,
  },
  {
    id: 'cand-sofia-abdullah',
    name: 'Sofia Abdullah',
    headline: 'Detail-obsessed CS student',
    university: 'Multimedia University',
    program: 'BCS Software Engineering',
    skills: [
      { name: 'Testing', level: 70 },
      { name: 'JavaScript', level: 68 },
      { name: 'Attention to Detail', level: 84 },
      { name: 'CI/CD', level: 52 },
    ],
    interests: ['qa', 'testing', 'quality'],
    aspirations: ['qa-engineer', 'software-engineer'],
    availabilityHoursPerWeek: 10,
    animalKey: 'ant',
    reliabilityScore: 95,
  },
  {
    id: 'cand-raj-kumar',
    name: 'Raj Kumar',
    headline: 'Restless generalist and part-time hacker',
    university: 'Asia Pacific University',
    program: 'BSc Computing',
    skills: [
      { name: 'Adaptability', level: 80 },
      { name: 'Communication', level: 66 },
      { name: 'Product Sense', level: 60 },
      { name: 'JavaScript', level: 64 },
    ],
    interests: ['startup', 'product', 'business'],
    aspirations: ['founder', 'product-manager', 'generalist'],
    availabilityHoursPerWeek: 14,
    animalKey: 'fox',
    reliabilityScore: 83,
  },
  {
    id: 'cand-mei-chen',
    name: 'Mei Chen',
    headline: 'People-first psychology grad',
    university: 'HELP University',
    program: 'BA Psychology',
    skills: [
      { name: 'Communication', level: 84 },
      { name: 'People Skills', level: 80 },
      { name: 'Organisation', level: 66 },
      { name: 'Analytics', level: 48 },
    ],
    interests: ['people', 'talent', 'business'],
    aspirations: ['people-ops', 'operations-manager'],
    availabilityHoursPerWeek: 7,
    animalKey: 'dolphin',
    reliabilityScore: 89,
  },
  {
    id: 'cand-arjun-menon',
    name: 'Arjun Menon',
    headline: 'Full-stack tinkerer',
    university: 'Sunway University',
    program: 'BSc Computer Science',
    skills: [
      { name: 'React', level: 70 },
      { name: 'TypeScript', level: 66 },
      { name: 'Go', level: 55 },
      { name: 'SQL', level: 62 },
    ],
    interests: ['full-stack', 'startup', 'product'],
    aspirations: ['software-engineer', 'generalist'],
    availabilityHoursPerWeek: 12,
    animalKey: 'octopus',
    reliabilityScore: 86,
  },
  {
    id: 'cand-nurul-izzati',
    name: 'Nurul Izzati',
    headline: 'Aspiring product leader',
    university: 'University of Nottingham Malaysia',
    program: 'BSc Business',
    skills: [
      { name: 'Product Sense', level: 64 },
      { name: 'Communication', level: 78 },
      { name: 'Analytics', level: 58 },
      { name: 'People Skills', level: 72 },
    ],
    interests: ['product', 'people', 'strategy'],
    aspirations: ['product-manager', 'people-ops'],
    availabilityHoursPerWeek: 9,
    animalKey: 'lion',
    reliabilityScore: 90,
  },
  {
    id: 'cand-james-lee',
    name: 'James Lee',
    headline: 'Deep-focus math and ML student',
    university: 'University of Malaya',
    program: 'BSc Mathematics',
    skills: [
      { name: 'Python', level: 78 },
      { name: 'Statistics', level: 82 },
      { name: 'Machine Learning', level: 66 },
      { name: 'SQL', level: 54 },
    ],
    interests: ['machine-learning', 'data', 'research'],
    aspirations: ['ml-engineer', 'data-scientist'],
    availabilityHoursPerWeek: 13,
    animalKey: 'tortoise',
    reliabilityScore: 93,
  },
  {
    id: 'cand-farah-idris',
    name: 'Farah Idris',
    headline: 'Creative coder and brand hobbyist',
    university: 'Limkokwing University',
    program: 'BA Creative Media',
    skills: [
      { name: 'Visual Design', level: 74 },
      { name: 'Figma', level: 70 },
      { name: 'Copywriting', level: 66 },
      { name: 'JavaScript', level: 50 },
    ],
    interests: ['design', 'brand', 'creative'],
    aspirations: ['designer', 'creative-director'],
    availabilityHoursPerWeek: 8,
    animalKey: 'peacock',
    reliabilityScore: 85,
  },
  {
    id: 'cand-kevin-wong',
    name: 'Kevin Wong',
    headline: 'Reliability-focused systems student',
    university: 'Universiti Sains Malaysia',
    program: 'BCS Computer Science',
    skills: [
      { name: 'Go', level: 58 },
      { name: 'SQL', level: 68 },
      { name: 'System Design', level: 62 },
      { name: 'Testing', level: 60 },
    ],
    interests: ['backend', 'infrastructure', 'distributed-systems'],
    aspirations: ['platform-engineer', 'software-engineer'],
    availabilityHoursPerWeek: 10,
    animalKey: 'beaver',
    reliabilityScore: 88,
  },
  {
    id: 'cand-leela-suppiah',
    name: 'Leela Suppiah',
    headline: 'Strategy-curious econ student',
    university: 'Monash University Malaysia',
    program: 'BA Economics',
    skills: [
      { name: 'Analytics', level: 70 },
      { name: 'Communication', level: 74 },
      { name: 'Product Sense', level: 58 },
      { name: 'Marketing', level: 60 },
    ],
    interests: ['strategy', 'business', 'growth'],
    aspirations: ['strategist', 'growth-marketer'],
    availabilityHoursPerWeek: 9,
    animalKey: 'eagle',
    reliabilityScore: 89,
  },
]

/* ================================================================== */
/*  University cohorts                                                */
/* ================================================================== */

const COHORT_A_ENGAGEMENTS: StudentEngagement[] = [
  {
    candidateId: 'cand-john-doe',
    name: 'John Doe',
    trackId: 'trk-fe-arch',
    trackTitle: 'Frontend Architecture Mentorship',
    org: 'Talentbank',
    status: 'on-track',
    progressPct: 67,
    weeksElapsed: 8,
    weeksTotal: 12,
    lastActivity: '1 day ago',
    reliabilityScore: 96,
    animalKey: 'beaver',
  },
  {
    candidateId: 'cand-arjun-menon',
    name: 'Arjun Menon',
    trackId: 'trk-startup-generalist',
    trackTitle: 'Startup Generalist Residency',
    org: 'Kapital DX',
    status: 'on-track',
    progressPct: 40,
    weeksElapsed: 4,
    weeksTotal: 10,
    lastActivity: '2 days ago',
    reliabilityScore: 86,
    animalKey: 'octopus',
  },
  {
    candidateId: 'cand-priya-nair',
    name: 'Priya Nair',
    trackId: 'trk-brand-design',
    trackTitle: 'Brand & Content Design Studio',
    org: 'AirAsia',
    status: 'needs-nudge',
    progressPct: 38,
    weeksElapsed: 4,
    weeksTotal: 8,
    lastActivity: '6 days ago',
    reliabilityScore: 90,
    animalKey: 'peacock',
  },
  {
    candidateId: 'cand-raj-kumar',
    name: 'Raj Kumar',
    trackId: 'trk-startup-generalist',
    trackTitle: 'Startup Generalist Residency',
    org: 'Kapital DX',
    status: 'at-risk',
    progressPct: 22,
    weeksElapsed: 5,
    weeksTotal: 10,
    lastActivity: '12 days ago',
    reliabilityScore: 83,
    animalKey: 'fox',
  },
  {
    candidateId: 'cand-marcus-tan',
    name: 'Marcus Tan',
    trackId: 'trk-product-strategy',
    trackTitle: 'Product Strategy Fellowship',
    org: 'Grab',
    status: 'on-track',
    progressPct: 55,
    weeksElapsed: 5,
    weeksTotal: 10,
    lastActivity: '3 days ago',
    reliabilityScore: 88,
    animalKey: 'eagle',
  },
  {
    candidateId: 'cand-sofia-abdullah',
    name: 'Sofia Abdullah',
    trackId: 'trk-qa-quality',
    trackTitle: 'Quality Engineering Apprenticeship',
    org: 'MoneyLion',
    status: 'on-track',
    progressPct: 58,
    weeksElapsed: 7,
    weeksTotal: 12,
    lastActivity: '1 day ago',
    reliabilityScore: 95,
    animalKey: 'ant',
  },
  {
    candidateId: 'cand-nurul-izzati',
    name: 'Nurul Izzati',
    trackId: null,
    trackTitle: null,
    org: null,
    status: 'needs-nudge',
    progressPct: 0,
    weeksElapsed: 0,
    weeksTotal: 0,
    lastActivity: '9 days ago',
    reliabilityScore: 90,
    animalKey: 'lion',
  },
]

const COHORT_B_ENGAGEMENTS: StudentEngagement[] = [
  {
    candidateId: 'cand-aisha-rahman',
    name: 'Aisha Rahman',
    trackId: 'trk-data-sci',
    trackTitle: 'Applied Data Science Track',
    org: 'Gamuda',
    status: 'on-track',
    progressPct: 60,
    weeksElapsed: 7,
    weeksTotal: 12,
    lastActivity: '1 day ago',
    reliabilityScore: 92,
    animalKey: 'owl',
  },
  {
    candidateId: 'cand-james-lee',
    name: 'James Lee',
    trackId: 'trk-data-sci',
    trackTitle: 'Applied Data Science Track',
    org: 'Gamuda',
    status: 'on-track',
    progressPct: 50,
    weeksElapsed: 6,
    weeksTotal: 12,
    lastActivity: '2 days ago',
    reliabilityScore: 93,
    animalKey: 'tortoise',
  },
  {
    candidateId: 'cand-wei-lim',
    name: 'Wei Lim',
    trackId: 'trk-backend-plat',
    trackTitle: 'Backend Platform Engineering',
    org: 'Setel',
    status: 'needs-nudge',
    progressPct: 33,
    weeksElapsed: 5,
    weeksTotal: 12,
    lastActivity: '7 days ago',
    reliabilityScore: 94,
    animalKey: 'tortoise',
  },
  {
    candidateId: 'cand-hana-yusof',
    name: 'Hana Yusof',
    trackId: 'trk-growth-mktg',
    trackTitle: 'Growth Marketing Sprint',
    org: 'Carsome',
    status: 'on-track',
    progressPct: 62,
    weeksElapsed: 5,
    weeksTotal: 8,
    lastActivity: '2 days ago',
    reliabilityScore: 87,
    animalKey: 'dolphin',
  },
  {
    candidateId: 'cand-daniel-ong',
    name: 'Daniel Ong',
    trackId: 'trk-ops-delivery',
    trackTitle: 'Operations & Delivery Track',
    org: 'Ninja Van',
    status: 'at-risk',
    progressPct: 30,
    weeksElapsed: 6,
    weeksTotal: 10,
    lastActivity: '14 days ago',
    reliabilityScore: 91,
    animalKey: 'wolf',
  },
  {
    candidateId: 'cand-kevin-wong',
    name: 'Kevin Wong',
    trackId: 'trk-backend-plat',
    trackTitle: 'Backend Platform Engineering',
    org: 'Setel',
    status: 'on-track',
    progressPct: 45,
    weeksElapsed: 6,
    weeksTotal: 12,
    lastActivity: '3 days ago',
    reliabilityScore: 88,
    animalKey: 'beaver',
  },
  {
    candidateId: 'cand-leela-suppiah',
    name: 'Leela Suppiah',
    trackId: 'trk-product-strategy',
    trackTitle: 'Product Strategy Fellowship',
    org: 'Grab',
    status: 'needs-nudge',
    progressPct: 35,
    weeksElapsed: 4,
    weeksTotal: 10,
    lastActivity: '8 days ago',
    reliabilityScore: 89,
    animalKey: 'eagle',
  },
]

export const COHORTS: Cohort[] = [
  {
    id: 'cohort-cs-26',
    name: 'Computer Science ’26',
    university: 'Sunway University',
    program: 'BSc Computer Science & Software Engineering',
    intakeYear: 2023,
    studentCount: 64,
    placedCount: 41,
    engagements: COHORT_A_ENGAGEMENTS,
  },
  {
    id: 'cohort-data-26',
    name: 'Data & Analytics ’26',
    university: 'University of Malaya',
    program: 'BSc Data Science, Statistics & Mathematics',
    intakeYear: 2023,
    studentCount: 52,
    placedCount: 33,
    engagements: COHORT_B_ENGAGEMENTS,
  },
]

/* ================================================================== */
/*  University metrics                                                */
/* ================================================================== */

export const MISMATCH_AVERTED: MismatchAverted = {
  averted: 29,
  totalExplorations: 74,
  rate: 39,
  estimatedHoursSaved: 8700,
  narrative:
    '29 of 74 track explorations ended with a student redirecting away from a path they had assumed was right for them — discovered through a few weeks of real work rather than years into a wrong-fit career.',
}

/**
 * Interest × domain intensity for the university heatmap. Values are 0..100
 * demand/interest intensity — how strongly students in the cohorts lean
 * toward each domain for each interest area.
 */
export const INTEREST_HEATMAP: InterestHeatmap = {
  rowLabel: 'Interest',
  colLabel: 'Domain',
  rows: ['Engineering', 'Data & AI', 'Product', 'Design', 'Growth', 'Operations'],
  cols: ['Startups', 'Big Tech', 'Fintech', 'Agencies', 'Enterprise'],
  values: [
    [78, 84, 72, 30, 55], // Engineering
    [62, 80, 74, 22, 68], // Data & AI
    [70, 66, 58, 40, 52], // Product
    [58, 48, 34, 88, 30], // Design
    [74, 52, 60, 70, 44], // Growth
    [48, 44, 56, 26, 72], // Operations
  ],
}
